services:
  postgresql:
    image: postgres:16.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=vehicle_triggers_api

  nats:
    image: nats:2.11-alpine
    command:
      - "-js"
      - "-sd"
      - "/data"
      - "-m"
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data

volumes:
  nats-data:
