// Code generated by MockGen. DO NOT EDIT.
// Source: metric_listener.go
//
// Generated by this command:
//
//	mockgen -source=metric_listener.go -destination=metric_listener_mock_test.go -package=metriclistener
//

// Package metriclistener is a generated GoMock package.
package metriclistener

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	cloudevent "github.com/DIMO-Network/cloudevent"
	vss "github.com/DIMO-Network/model-garage/pkg/vss"
	webhook "github.com/DIMO-Network/vehicle-triggers-api/internal/controllers/webhook"
	models "github.com/DIMO-Network/vehicle-triggers-api/internal/db/models"
	triggerevaluator "github.com/DIMO-Network/vehicle-triggers-api/internal/services/triggerevaluator"
	webhookcache "github.com/DIMO-Network/vehicle-triggers-api/internal/services/webhookcache"
	cel "github.com/google/cel-go/cel"
	gomock "go.uber.org/mock/gomock"
)

// MockNATSBridge is a mock of NATSBridge interface.
type MockNATSBridge struct {
	ctrl     *gomock.Controller
	recorder *MockNATSBridgeMockRecorder
	isgomock struct{}
}

// MockNATSBridgeMockRecorder is the mock recorder for MockNATSBridge.
type MockNATSBridgeMockRecorder struct {
	mock *MockNATSBridge
}

// NewMockNATSBridge creates a new mock instance.
func NewMockNATSBridge(ctrl *gomock.Controller) *MockNATSBridge {
	mock := &MockNATSBridge{ctrl: ctrl}
	mock.recorder = &MockNATSBridgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSBridge) EXPECT() *MockNATSBridgeMockRecorder {
	return m.recorder
}

// PublishEvents mocks base method.
func (m *MockNATSBridge) PublishEvents(ctx context.Context, ce vss.EventCloudEvent) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvents", ctx, ce)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishEvents indicates an expected call of PublishEvents.
func (mr *MockNATSBridgeMockRecorder) PublishEvents(ctx, ce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvents", reflect.TypeOf((*MockNATSBridge)(nil).PublishEvents), ctx, ce)
}

// PublishSignals mocks base method.
func (m *MockNATSBridge) PublishSignals(ctx context.Context, ce vss.SignalCloudEvent) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSignals", ctx, ce)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishSignals indicates an expected call of PublishSignals.
func (mr *MockNATSBridgeMockRecorder) PublishSignals(ctx, ce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSignals", reflect.TypeOf((*MockNATSBridge)(nil).PublishSignals), ctx, ce)
}

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// PublishTriggerFired mocks base method.
func (m *MockAuditPublisher) PublishTriggerFired(ctx context.Context, devLicense string, record []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTriggerFired", ctx, devLicense, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTriggerFired indicates an expected call of PublishTriggerFired.
func (mr *MockAuditPublisherMockRecorder) PublishTriggerFired(ctx, devLicense, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTriggerFired", reflect.TypeOf((*MockAuditPublisher)(nil).PublishTriggerFired), ctx, devLicense, record)
}

// MockStateRecorder is a mock of StateRecorder interface.
type MockStateRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockStateRecorderMockRecorder
	isgomock struct{}
}

// MockStateRecorderMockRecorder is the mock recorder for MockStateRecorder.
type MockStateRecorderMockRecorder struct {
	mock *MockStateRecorder
}

// NewMockStateRecorder creates a new mock instance.
func NewMockStateRecorder(ctrl *gomock.Controller) *MockStateRecorder {
	mock := &MockStateRecorder{ctrl: ctrl}
	mock.recorder = &MockStateRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateRecorder) EXPECT() *MockStateRecorderMockRecorder {
	return m.recorder
}

// RecordFire mocks base method.
func (m *MockStateRecorder) RecordFire(ctx context.Context, triggerID, metricName string, vehicleDID cloudevent.ERC721DID, at time.Time, snapshot json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFire", ctx, triggerID, metricName, vehicleDID, at, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFire indicates an expected call of RecordFire.
func (mr *MockStateRecorderMockRecorder) RecordFire(ctx, triggerID, metricName, vehicleDID, at, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFire", reflect.TypeOf((*MockStateRecorder)(nil).RecordFire), ctx, triggerID, metricName, vehicleDID, at, snapshot)
}

// MockTriggerRepo is a mock of TriggerRepo interface.
type MockTriggerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerRepoMockRecorder
	isgomock struct{}
}

// MockTriggerRepoMockRecorder is the mock recorder for MockTriggerRepo.
type MockTriggerRepoMockRecorder struct {
	mock *MockTriggerRepo
}

// NewMockTriggerRepo creates a new mock instance.
func NewMockTriggerRepo(ctrl *gomock.Controller) *MockTriggerRepo {
	mock := &MockTriggerRepo{ctrl: ctrl}
	mock.recorder = &MockTriggerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerRepo) EXPECT() *MockTriggerRepoMockRecorder {
	return m.recorder
}

// DeleteVehicleSubscription mocks base method.
func (m *MockTriggerRepo) DeleteVehicleSubscription(ctx context.Context, triggerID string, assetDid cloudevent.ERC721DID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVehicleSubscription", ctx, triggerID, assetDid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteVehicleSubscription indicates an expected call of DeleteVehicleSubscription.
func (mr *MockTriggerRepoMockRecorder) DeleteVehicleSubscription(ctx, triggerID, assetDid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVehicleSubscription", reflect.TypeOf((*MockTriggerRepo)(nil).DeleteVehicleSubscription), ctx, triggerID, assetDid)
}

// IncrementTriggerFailureCount mocks base method.
func (m *MockTriggerRepo) IncrementTriggerFailureCount(ctx context.Context, trigger *models.Trigger, failureReason error, maxFailureCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTriggerFailureCount", ctx, trigger, failureReason, maxFailureCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementTriggerFailureCount indicates an expected call of IncrementTriggerFailureCount.
func (mr *MockTriggerRepoMockRecorder) IncrementTriggerFailureCount(ctx, trigger, failureReason, maxFailureCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTriggerFailureCount", reflect.TypeOf((*MockTriggerRepo)(nil).IncrementTriggerFailureCount), ctx, trigger, failureReason, maxFailureCount)
}

// ResetTriggerFailureCount mocks base method.
func (m *MockTriggerRepo) ResetTriggerFailureCount(ctx context.Context, trigger *models.Trigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetTriggerFailureCount", ctx, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetTriggerFailureCount indicates an expected call of ResetTriggerFailureCount.
func (mr *MockTriggerRepoMockRecorder) ResetTriggerFailureCount(ctx, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetTriggerFailureCount", reflect.TypeOf((*MockTriggerRepo)(nil).ResetTriggerFailureCount), ctx, trigger)
}

// MockWebhookSender is a mock of WebhookSender interface.
type MockWebhookSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSenderMockRecorder
	isgomock struct{}
}

// MockWebhookSenderMockRecorder is the mock recorder for MockWebhookSender.
type MockWebhookSenderMockRecorder struct {
	mock *MockWebhookSender
}

// NewMockWebhookSender creates a new mock instance.
func NewMockWebhookSender(ctrl *gomock.Controller) *MockWebhookSender {
	mock := &MockWebhookSender{ctrl: ctrl}
	mock.recorder = &MockWebhookSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSender) EXPECT() *MockWebhookSenderMockRecorder {
	return m.recorder
}

// SendWebhook mocks base method.
func (m *MockWebhookSender) SendWebhook(ctx context.Context, trigger *models.Trigger, payload *cloudevent.CloudEvent[webhook.WebhookPayload]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWebhook", ctx, trigger, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWebhook indicates an expected call of SendWebhook.
func (mr *MockWebhookSenderMockRecorder) SendWebhook(ctx, trigger, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWebhook", reflect.TypeOf((*MockWebhookSender)(nil).SendWebhook), ctx, trigger, payload)
}

// MockWebhookFailureManager is a mock of WebhookFailureManager interface.
type MockWebhookFailureManager struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookFailureManagerMockRecorder
	isgomock struct{}
}

// MockWebhookFailureManagerMockRecorder is the mock recorder for MockWebhookFailureManager.
type MockWebhookFailureManagerMockRecorder struct {
	mock *MockWebhookFailureManager
}

// NewMockWebhookFailureManager creates a new mock instance.
func NewMockWebhookFailureManager(ctrl *gomock.Controller) *MockWebhookFailureManager {
	mock := &MockWebhookFailureManager{ctrl: ctrl}
	mock.recorder = &MockWebhookFailureManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookFailureManager) EXPECT() *MockWebhookFailureManagerMockRecorder {
	return m.recorder
}

// HandleWebhookFailure mocks base method.
func (m *MockWebhookFailureManager) HandleWebhookFailure(ctx context.Context, trigger *models.Trigger, failureReason error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhookFailure", ctx, trigger, failureReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhookFailure indicates an expected call of HandleWebhookFailure.
func (mr *MockWebhookFailureManagerMockRecorder) HandleWebhookFailure(ctx, trigger, failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhookFailure", reflect.TypeOf((*MockWebhookFailureManager)(nil).HandleWebhookFailure), ctx, trigger, failureReason)
}

// HandleWebhookSuccess mocks base method.
func (m *MockWebhookFailureManager) HandleWebhookSuccess(ctx context.Context, trigger *models.Trigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhookSuccess", ctx, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhookSuccess indicates an expected call of HandleWebhookSuccess.
func (mr *MockWebhookFailureManagerMockRecorder) HandleWebhookSuccess(ctx, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhookSuccess", reflect.TypeOf((*MockWebhookFailureManager)(nil).HandleWebhookSuccess), ctx, trigger)
}

// ShouldAttemptWebhook mocks base method.
func (m *MockWebhookFailureManager) ShouldAttemptWebhook(trigger *models.Trigger) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldAttemptWebhook", trigger)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldAttemptWebhook indicates an expected call of ShouldAttemptWebhook.
func (mr *MockWebhookFailureManagerMockRecorder) ShouldAttemptWebhook(trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldAttemptWebhook", reflect.TypeOf((*MockWebhookFailureManager)(nil).ShouldAttemptWebhook), trigger)
}

// MockTriggerEvaluator is a mock of TriggerEvaluator interface.
type MockTriggerEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerEvaluatorMockRecorder
	isgomock struct{}
}

// MockTriggerEvaluatorMockRecorder is the mock recorder for MockTriggerEvaluator.
type MockTriggerEvaluatorMockRecorder struct {
	mock *MockTriggerEvaluator
}

// NewMockTriggerEvaluator creates a new mock instance.
func NewMockTriggerEvaluator(ctrl *gomock.Controller) *MockTriggerEvaluator {
	mock := &MockTriggerEvaluator{ctrl: ctrl}
	mock.recorder = &MockTriggerEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerEvaluator) EXPECT() *MockTriggerEvaluatorMockRecorder {
	return m.recorder
}

// EvaluateEventTrigger mocks base method.
func (m *MockTriggerEvaluator) EvaluateEventTrigger(ctx context.Context, trigger *models.Trigger, program cel.Program, ev *triggerevaluator.EventEvaluationData) (*triggerevaluator.TriggerEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateEventTrigger", ctx, trigger, program, ev)
	ret0, _ := ret[0].(*triggerevaluator.TriggerEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateEventTrigger indicates an expected call of EvaluateEventTrigger.
func (mr *MockTriggerEvaluatorMockRecorder) EvaluateEventTrigger(ctx, trigger, program, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateEventTrigger", reflect.TypeOf((*MockTriggerEvaluator)(nil).EvaluateEventTrigger), ctx, trigger, program, ev)
}

// EvaluateSignalTrigger mocks base method.
func (m *MockTriggerEvaluator) EvaluateSignalTrigger(ctx context.Context, trigger *models.Trigger, program cel.Program, signal *triggerevaluator.SignalEvaluationData) (*triggerevaluator.TriggerEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateSignalTrigger", ctx, trigger, program, signal)
	ret0, _ := ret[0].(*triggerevaluator.TriggerEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateSignalTrigger indicates an expected call of EvaluateSignalTrigger.
func (mr *MockTriggerEvaluatorMockRecorder) EvaluateSignalTrigger(ctx, trigger, program, signal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateSignalTrigger", reflect.TypeOf((*MockTriggerEvaluator)(nil).EvaluateSignalTrigger), ctx, trigger, program, signal)
}

// MockWebhookCache is a mock of WebhookCache interface.
type MockWebhookCache struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookCacheMockRecorder
	isgomock struct{}
}

// MockWebhookCacheMockRecorder is the mock recorder for MockWebhookCache.
type MockWebhookCacheMockRecorder struct {
	mock *MockWebhookCache
}

// NewMockWebhookCache creates a new mock instance.
func NewMockWebhookCache(ctrl *gomock.Controller) *MockWebhookCache {
	mock := &MockWebhookCache{ctrl: ctrl}
	mock.recorder = &MockWebhookCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookCache) EXPECT() *MockWebhookCacheMockRecorder {
	return m.recorder
}

// GetWebhooks mocks base method.
func (m *MockWebhookCache) GetWebhooks(vehicleDID, service, metricName string) []*webhookcache.Webhook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhooks", vehicleDID, service, metricName)
	ret0, _ := ret[0].([]*webhookcache.Webhook)
	return ret0
}

// GetWebhooks indicates an expected call of GetWebhooks.
func (mr *MockWebhookCacheMockRecorder) GetWebhooks(vehicleDID, service, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhooks", reflect.TypeOf((*MockWebhookCache)(nil).GetWebhooks), vehicleDID, service, metricName)
}

// ScheduleRefresh mocks base method.
func (m *MockWebhookCache) ScheduleRefresh(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ScheduleRefresh", ctx)
}

// ScheduleRefresh indicates an expected call of ScheduleRefresh.
func (mr *MockWebhookCacheMockRecorder) ScheduleRefresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleRefresh", reflect.TypeOf((*MockWebhookCache)(nil).ScheduleRefresh), ctx)
}
