replicaCount: 1
image:
  repository: dimozone/vehicle-triggers-api
  pullPolicy: IfNotPresent
  tag: bf9af18
imagePullSecrets: []
command:
  - /app
  - '-migrations=up -v'
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
env:
  ENVIRONMENT: dev
  PORT: 8080
  MON_PORT: 8888
  ENABLE_PPROF: false
  LOG_LEVEL: debug
  DB_PORT: '5432'
  DB_NAME: vehicle_triggers_api
  DB_SSL_MODE: require
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  SERVICE_NAME: vehicle-triggers-api
  JWK_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  IDENTITY_API_URL: https://identity-api.dev.dimo.zone/query
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  DEVICE_SIGNALS_TOPIC: topic.device.signals
  DEVICE_EVENTS_TOPIC: topic.device.events
  VEHICLE_NFT_ADDRESS: '0x45fbCD3ef7361d156e8b16F5538AE36DEdf61Da8'
  DIMO_REGISTRY_CHAIN_ID': 80002
  MAX_WEBHOOK_FAILURE_COUNT: 5
  CACHE_DEBOUNCE_TIME: 5s
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '3'
    external-dns.alpha.kubernetes.io/hostname: vehicle-triggers-api.dev.dimo.zone
  hosts:
    - host: vehicle-triggers-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
serviceMonitor:
  enabled: false
  path: /metrics
  port: mon-http
  interval: 30s
