// Code generated by MockGen. DO NOT EDIT.
// Source: trigger_evaluator.go
//
// Generated by this command:
//
//	mockgen -source=trigger_evaluator.go -destination=trigger_evaluator_mock_test.go -package=triggerevaluator
//

// Package triggerevaluator is a generated GoMock package.
package triggerevaluator

import (
	context "context"
	reflect "reflect"

	cloudevent "github.com/DIMO-Network/cloudevent"
	triggerstate "github.com/DIMO-Network/vehicle-triggers-api/internal/services/triggerstate"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
	isgomock struct{}
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// LastFire mocks base method.
func (m *MockStateStore) LastFire(ctx context.Context, triggerID string, vehicleDID cloudevent.ERC721DID) (triggerstate.Record, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastFire", ctx, triggerID, vehicleDID)
	ret0, _ := ret[0].(triggerstate.Record)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LastFire indicates an expected call of LastFire.
func (mr *MockStateStoreMockRecorder) LastFire(ctx, triggerID, vehicleDID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastFire", reflect.TypeOf((*MockStateStore)(nil).LastFire), ctx, triggerID, vehicleDID)
}

// LastMetric mocks base method.
func (m *MockStateStore) LastMetric(ctx context.Context, vehicleDID cloudevent.ERC721DID, metricName string) (triggerstate.MetricRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastMetric", ctx, vehicleDID, metricName)
	ret0, _ := ret[0].(triggerstate.MetricRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LastMetric indicates an expected call of LastMetric.
func (mr *MockStateStoreMockRecorder) LastMetric(ctx, vehicleDID, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastMetric", reflect.TypeOf((*MockStateStore)(nil).LastMetric), ctx, vehicleDID, metricName)
}

// MockTokenExchangeClient is a mock of TokenExchangeClient interface.
type MockTokenExchangeClient struct {
	ctrl     *gomock.Controller
	recorder *MockTokenExchangeClientMockRecorder
	isgomock struct{}
}

// MockTokenExchangeClientMockRecorder is the mock recorder for MockTokenExchangeClient.
type MockTokenExchangeClientMockRecorder struct {
	mock *MockTokenExchangeClient
}

// NewMockTokenExchangeClient creates a new mock instance.
func NewMockTokenExchangeClient(ctrl *gomock.Controller) *MockTokenExchangeClient {
	mock := &MockTokenExchangeClient{ctrl: ctrl}
	mock.recorder = &MockTokenExchangeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenExchangeClient) EXPECT() *MockTokenExchangeClientMockRecorder {
	return m.recorder
}

// HasVehiclePermissions mocks base method.
func (m *MockTokenExchangeClient) HasVehiclePermissions(ctx context.Context, vehicleDID cloudevent.ERC721DID, developerLicense common.Address, permissions []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasVehiclePermissions", ctx, vehicleDID, developerLicense, permissions)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasVehiclePermissions indicates an expected call of HasVehiclePermissions.
func (mr *MockTokenExchangeClientMockRecorder) HasVehiclePermissions(ctx, vehicleDID, developerLicense, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVehiclePermissions", reflect.TypeOf((*MockTokenExchangeClient)(nil).HasVehiclePermissions), ctx, vehicleDID, developerLicense, permissions)
}
