// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeveloperLicenses string
	EventLogs         string
	EventVehicles     string
	Events            string
}{
	DeveloperLicenses: "developer_licenses",
	EventLogs:         "event_logs",
	EventVehicles:     "event_vehicles",
	Events:            "events",
}
