// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EventLogs     string
	EventVehicles string
	Triggers      string
}{
	EventLogs:     "event_logs",
	EventVehicles: "event_vehicles",
	Triggers:      "triggers",
}
