name: buildpushdev
on:
  push:
    branches:
      - main
env:
  APP_NAME: vehicle-triggers-api

jobs:
  build:
    name: buildpushdev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          push: true
          platforms: linux/amd64
          tags: dimozone/${{ env.APP_NAME }}:${{ steps.slug.outputs.sha7 }}, dimozone/${{ env.APP_NAME }}:latest

      - name: Update Image Version in the worker HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: "charts/${{ env.APP_NAME }}/values.yaml"
          propertyPath: "image.tag"
          value: ${{ steps.slug.outputs.sha7 }}
          branch: main
          message: "Update Image Version to ${{ steps.slug.outputs.sha7 }}"
